INSERT INTO PANTRY (ID, QUANTITY) VALUES ('iQpqxKidJjh1CqlE2dhO', '10.0 lb');
INSERT INTO PANTRY (ID, QUANTITY) VALUES ('ja2f039jawoiefj029JG', '3.0 lb');
INSERT INTO PANTRY (ID, QUANTITY) VALUES ('qycdI5tQqO8Tudsxzcba', '20.0 g');
INSERT INTO PANTRY (ID, QUANTITY) VALUES ('ja2f039jawoiefj029JB', '7.0 lb');
INSERT INTO PANTRY (ID, QUANTITY) VALUES ('xEBMC4hTrItjPVgsnL49', '20.0 l');